# By defining this StorageClass, we can auto-provision EBS volumes for PVCs
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2