apiVersion: v1
kind: Service
metadata:
  name: zookeeper-external
  labels:
    service: zookeeper-external
spec:
  ports:
    - port: 2181
      targetPort: 2181
      name: zk-client
  type: LoadBalancer
  selector:
    app: zk