apiVersion: v1
kind: ConfigMap
metadata:
  name: schemaregistry-config
data:
  SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry.mydomain.com"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:80"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://broker1.mydomain.com:9092,PLAINTEXT://broker2.mydomain.com:9092,PLAINTEXT://broker3.mydomain.com:9092"