apiVersion: v1
kind: ConfigMap
metadata:
  name: restproxy-config
data:
  KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://broker1.mydomain.com:9092,PLAINTEXT://broker2.mydomain.com:9092,PLAINTEXT://broker3.mydomain.com:9092,PLAINTEXT://broker4.mydomain.com:9092,PLAINTEXT://broker5.mydomain.com:9092"
  KAFKA_REST_LISTENERS: "http://0.0.0.0:80"
  KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry.mydomain.com"
  KAFKA_REST_HOST_NAME: "restproxy.mydomain.com"
