apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: restproxy
  labels:
    service: restproxy
spec:
  ports:
    - name: listener
      port: 80
  selector:
    app: restproxy
